### ISSUE TITLE
Drop Python 2 altogether

### ISSUE THREAD

**Issue by s-martin** [MiczFlor/RPi-Jukebox-RFID#796]
Some code was still Python 2 and some dependencies already dropped Python 2 support, which was causing issues, e.g. #783, #784.

To address this Python 2 should be removed altogether. 

On develop this has already been done for many parts of the code base. Currently Python2 packages are still installed.

For master a PR #795 was also opened.
For remaining tasks on develop PR #801 was opened.

This ticket should collect all necessary tasks left.

- [x] ~~force all services to use Python3 with prefix `python3` (master & develop)~~ not necessary, we use shebang for python3 in py scripts
- [x] check all py  files not ending with .py for Python3 compatibility (~~this is not done by flake8~~ **flake8 checks this now**), master & develop
- [x] upgrade Mopidy to 3 on Buster #803 
- [x] remove installation of Python2 packages from ~~stretch &~~ buster installation scripts (~~master &~~ develop) #849 
- [x] check installation script on master #843
- [x] check, if systemctl scripts now use only the python scripts directly without path to the executable (shebang is enough). This should be consistent on `master` and `develop` #848

**Comment by s-martin** [comment]
Maybe we should keep the installation scripts for stretch as it is.

For buster the mopidy3 script could be merged to default.sh first

**Comment by s-martin** [comment]
There seems to be an issue with mopidy-iris 3.43, which we currently have to use, because it’s the last python 2 version. See #759.

So we should fix this better sooner than later.

**Comment by s-martin** [comment]
I think it may be better to not change anything on stretch, existing installations probably work and for new installations buster should be used anyway.

**Comment by s-martin** [comment]
On master some parts where missing, see #842.

Maybe #822 needs to be merged to master.


Issue is master still needs Mopidy stuff to be python2, but our code is now python 3. Right now the install script on master just install python 2.7 packages.

**Comment by s-martin** [comment]
> On master some parts where missing, see #842.
> 
> Maybe #822 needs to be merged to master.
> 
> Issue is master still needs Mopidy stuff to be python2, but our code is now python 3. Right now the install script on master just install python 2.7 packages.

Fixed this with #843

**Comment by s-martin** [comment]
All Python 2 dependencies have been removed from buster on develop.
