### ISSUE TITLE
🚀 | move music and playlist directories

### ISSUE THREAD

**Issue by ZyanKLee** [MiczFlor/RPi-Jukebox-RFID#797]
### What functionality would you like to see in your phoniebox?

To separate the phoniebox code from it's payload, we should not use a subdir of `RPi-Jukebox-RFID` to store data.

### How do you envision the feature to work from a users perspective?

There is a common understanding, that music goes to `~/Music` on desktop environments. IMHO, we should stick to that to make it easier to find for users.
The same concept should be used for playlists: `~/Playlists`

### TODO

* [ ] Migration path for existing installations
* [ ] Documentation has to be modified to reflect this (buzzwords to remember: nfs, cifs, samba, backup, sync)
* [ ] Config changes for mpd, mopidy, web interface, etc

**Comment by Huseriato** [comment]
I think this feature will break hundreds of phonieboxes and leaves confused users behind. Anyone, who is just executing command lines that you're giving him or her, does not understand, what is happening. If you really consider to move files, there should be a really good migration path, that moves configuration files automatically and adjusts all configuration the user might done. From what I've seen in the code, it will be really hard to create a 100% solution for this.

I'm with you, that in a well designed software the config files are something that should be stored separately from the application. But we're here talking about a little Raspberry PI, which has only one function in this situation (play music and audio files for the kids). So in a matter of design aspect it is really cool to separate this. But in the matter of function and unnecessary changes this will break function and you'll gain nothing.

If you ever want to change this: Do it in version 3.0. May be in a separate project, where you can make some things better, that are currently not well designed. I took a longer look in the code. There are situations, where PHP calls a BASH that calls a PYTHON which uses BASH commands.

So Phoniebox works as it is. I'm looking forward for a version 3.0. But please, don't change this.
